### ISSUE TITLE
signalK-geofence-switch

### ISSUE THREAD

**Issue by jjskaife** [SignalK/node-red-embedded#18]
Is it possible to dynamically change the lat/lon of the geofence center through an input msg?

**Comment by sbender9** [comment]
Not currently possible, but I had someone else requests this. I'll go ahead and add it...

**Comment by sbender9** [comment]
The way I have implemented this is too allow two different inputs into gefence-switch. One would send a msg with the topic "signalk-config", this would contain json with lat/lon and optionally distance. Would that work for you?

**Comment by jjskaife** [comment]
that sounds perfect. thanks for the great job on this.

**Comment by sbender9** [comment]
ok, I published this. To get the update:

```
cd ~/.signalk
npm install  @signalk/node-red-embedded@2.16.0
```
