### ISSUE TITLE
Signalk-send-pathvalue

### ISSUE THREAD

**Issue by Darkleg** [SignalK/node-red-embedded#21]
Hi 
I think I've populated the node correctly (topic,path) but only get: "TypeError: Cannot read property 'handleMessage; of defined"

Would really appreciate some guidance. Have attached a simplified flow, near to what I'm trying achieve.

[Failed flows.docx](https://github.com/SignalK/node-red-embedded/files/5829151/Failed.flows.docx)

**Comment by sbender9** [comment]
It looks like your using the Signal K pallet in a standalone node red install. You have to use the signalk-node-red plugin on your server and use the node red instance that is running in the SK server.

**Comment by Darkleg** [comment]
I really appreciate the rapid and informative knowledgeable response..saving a lot of frustration.....That has diffidently correct ...(sorted), genius!

**Comment by tkurki** [comment]
Can we detect that we are in standalone and show something informative?

**Comment by Darkleg** [comment]
Making a bit of progress with my understanding of the signalk workings until.........The notification example works fine (data stream plaka.log) have attempted to replicate with a fuel level indicator...via the WS gauge also works fine.  But can't get subscribe node to send...have attached a few screens which I hope clarify my predicament?

Would appreciate some guidance.  Thank you.

![SignalK Server](https://user-images.githubusercontent.com/77612400/107985438-f5e92280-6fc1-11eb-9cf9-15ef0c50cfed.png)
![Notification_Alarm](https://user-images.githubusercontent.com/77612400/107985444-fa154000-6fc1-11eb-9919-a55b8bb27acc.png)

**Comment by sbender9** [comment]
Can click on one of the subscribe node and screenshot so I can see how it's setup?

**Comment by Darkleg** [comment]
Hi
![Opened subscribe](https://user-images.githubusercontent.com/77612400/108037746-f02b2580-7031-11eb-88f7-19b53512aa93.png)

**Comment by sbender9** [comment]
Looks ok. Can you export and share the nodes involved here?

**Comment by Darkleg** [comment]
Hoping this is the request:

[{"id":"c78652b5.a73b7","type":"signalk-subscribe","z":"38336563.2cc8e2","name":"tanks.fuel.level.currentLevel","mode":"sendAll","flatten":true,"context":"vessels.self","path":"tanks.fuel.level.currentLevel","source":"","period":1000,"x":180,"y":260,"wires":[["db2bf9c9.50a308"]]},{"id":"db2bf9c9.50a308","type":"switch","z":"38336563.2cc8e2","name":"Level","property":"payload","propertyType":"msg","rules":[{"t":"lt","v":"10","vt":"num"}],"checkall":"true","repair":false,"outputs":1,"x":410,"y":260,"wires":[["b85f3ec4.70399"]]},{"id":"b85f3ec4.70399","type":"signalk-send-notification","z":"38336563.2cc8e2","name":"send alarm","path":"highFuelLevel","state":"normal","message":"The tank is above 50%","visual":true,"sound":true,"source":"","x":630,"y":260,"wires":[]}]

**Comment by sbender9** [comment]
Can you get me the nodes that send the value also?

**Comment by Darkleg** [comment]
Flow below. From ADS1115 0x48_2



![Sender SS](https://user-images.githubusercontent.com/77612400/108114591-e5ec4400-7090-11eb-8132-3bf65d548583.png)
[{"id":"2e4fe0e1.8e0cc","type":"ads1x15-raspi","z":"356a2cdb.a50e04","property":"payload","name":"0x48_2","chip":"IC_ADS1115","i2c_address":"ADDRESS_0x48","channel":"CHANNEL_2","samplesPerSecond0":"SPS_920","samplesPerSecond1":"SPS_128","progGainAmp":"PGA_4_096V","x":225,"y":325,"wires":[["2d131494.34fd7c","84643c6b.56256"]]},{"id":"2d131494.34fd7c","type":"change","z":"356a2cdb.a50e04","name":"","rules":[{"t":"set","p":"payload","pt":"msg","to":"payload.voltage","tot":"msg"}],"action":"","property":"","from":"","to":"","reg":false,"x":430,"y":325,"wires":[["dff9f17b.6c323"]]},{"id":"dff9f17b.6c323","type":"function","z":"356a2cdb.a50e04","name":"convert","func":"var numInput = Number(msg.payload)*4.84848484;\n//convert to round number\nmsg.payload = Math.round(numInput*1000)/1000\nreturn msg;","outputs":1,"noerr":0,"initialize":"","finalize":"","x":610,"y":325,"wires":[["c9e25aff.215608"]]},{"id":"c9e25aff.215608","type":"function","z":"356a2cdb.a50e04","name":"tanks.fuel.level.currentLevel","func":"msg.topic = \"tanks.fuel.level.currentLevel\"\nreturn msg;","outputs":1,"noerr":0,"initialize":"","finalize":"","x":820,"y":325,"wires":[["7a9ccdf2.f5f4e4"]]},{"id":"7a9ccdf2.f5f4e4","type":"signalk-send-pathvalue","z":"356a2cdb.a50e04","name":"","source":"","x":1195,"y":325,"wires":[]}]

**Comment by sbender9** [comment]
OK, I need to go back and figure out why I did this, but by default data from node-red is ignored...

Change the $Source in your subscribe node to `signalk-node-red` and it should work.

**Comment by Darkleg** [comment]
Works brilliantly...many thanks for your help and patience...really appreciate it.

**Comment by joeltaylorPAVS** [comment]
Hi @sbender9 

I appear to be having the same issue as above and have tried the signalk-node-red trick with no luck. could be a user error but i cannot get an output from the subscribe node. please see attached screen grabs of node and the server data source. the node red instance is hosted on the signalk server as a plugin.

![image](https://user-images.githubusercontent.com/30060597/116381375-2ec23500-a858-11eb-9d1c-ef86f00e6cd6.png)
![image](https://user-images.githubusercontent.com/30060597/116381656-734dd080-a858-11eb-8a71-038e0b48e5eb.png)
