### ISSUE TITLE
Using external functions in node red

### ISSUE THREAD

**Issue by mcdonaldajr** [SignalK/node-red-embedded#28]
I would like to set functionExternalModules to true in the settings.js file, so I can call external functions easily.
See https://nodered.org/docs/user-guide/writing-functions for details.
Could you set this by default please?

**Comment by sbender9** [comment]
You should be able to set this in the plugin config. Just add it under "Node Red Settings"

**Comment by mcdonaldajr** [comment]
Thank You. Works well.
