### ISSUE TITLE
Retrieve stale/out-dated data

### ISSUE THREAD

**Issue by ryansabin** [SignalK/node-red-embedded#35]
I need to retrieve some data from the defaults plugin. Like design.draft and design.length. These data points are only updated on restart so the Subscribe node will not receive the data. Is there any way to query the data using Signal K Node Red plugins.

**Comment by sbender9** [comment]
let app = global.get('app') 

let sog = app.getSelfPath('navigation.speedOverGround.value')

**Comment by ryansabin** [comment]
That works. Thanks for the info. It would be nice to have a node that returns this data.

Thanks!
